### ISSUE TITLE
Solargraph not working

### ISSUE THREAD

**Issue by talltechy** [castwide/atom-solargraph#10]
Atom release 1.31.1
Solargraph is listening PORT=64472 PID=12300
Plugin installed from atom - latest release per atom

Getting no messages, doing ctrl+alt+o does nothing

**Comment by noelrappin** [comment]
Ditto

**Comment by foreverqihe** [comment]
It doesn't start solargraph server.
Atom 1.31.2

**Comment by foreverqihe** [comment]
It works now after upgrading to Atom 1.32.0
