### ISSUE TITLE
Getting undefined method `sources' for "":String on startup

### ISSUE THREAD

**Issue by aergonaut** [castwide/atom-solargraph#11]
Not sure how to properly debug or if this is a problem with the gem instead of the Atom package.

When I start Atom, I notice in the console there are a lot of warnings output with this message: undefined method `sources' for "":String

My environment:
* Ruby 2.5.1
* rbenv
* bundler
* ruby-solargraph 0.3.0
* solargraph 0.30.2

**Comment by castwide** [comment]
This should be resolved in the latest version of the gem (0.31.3). Right now I'm unable to reproduce it.

**Comment by aergonaut** [comment]
Thanks @castwide. Works like a charm!
