### ISSUE TITLE
Not working in Atom for me

### ISSUE THREAD

**Issue by sanchit121** [castwide/atom-solargraph#2]
Just followed basic steps. No autocomplete results showing. Neither any error. have installed solargraph gem also

**Comment by castwide** [comment]
Are you editing a file with an .rb extension? The console should report that Solargraph was activated even if there weren't any errors.

**Comment by sanchit121** [comment]
Hi castwide, thanks for your kind input Here are console logs. please help.

Solargraph package activated.
SolargraphServer.js [sm]:32 /Users/sanchitagarwal/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem solargraph (>= 0.a) (Gem::GemNotFoundException)

SolargraphServer.js [sm]:32 	from /Users/sanchitagarwal/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
	from /Users/sanchitagarwal/.rvm/gems/ruby-2.4.2/bin/solargraph:23:in `<main>'
	from /Users/sanchitagarwal/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sanchitagarwal/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

Thanks

**Comment by castwide** [comment]
Thanks, @sanchit121. Since you're using RVM, you may need to make sure the Solargraph gem is installed on the same version of the gem that Atom is using. The errors indicate it's using Ruby 2.4.1. You can run `ruby -v` or `which ruby` from a command line for more information.

Ruby managers like RVM are known to cause issues with Solargraph in certain environments. I'm in the process of fixing that problem in the VS Code extension and will port the fix to the Atom package in the next version.

**Comment by castwide** [comment]
Version 0.1.1 of the Atom package is published. This update should resolve issues with Ruby install managers and provide some minor improvements to performance.

**Comment by sanchit121** [comment]
Yup, thanks for fixing, its working for me now. Thanks

**Comment by sanchit121** [comment]
Hi, it gives context specific suggestions also, like i have Article model
which has title, description, so will it give Article.find_by_title.? etc.

**Comment by castwide** [comment]
Solargraph uses a combination of static analysis and YARD documentation to provide suggestions. Magic methods--i.e., anything injected dynamically at runtime--can't always be detected statically. Rails is especially prone to this limitation.

One way I'm trying to improve dynamic method detection is the runtime plugin as described in the [gem's README](https://github.com/castwide/solargraph), but it's highly experimental, and its detection of Rails magic methods is incomplete.
